<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
    'Home' => '首页',

     //动作
    'Login'=>'登录',
    'Logout'=>'登出',
    
     //用户功能
    'User Menu' => '用户菜单',

     //用户
    'Username'=>'用户名',
    'Password'=>'密码',
    'Nickname'=>'昵称',
    'Avatar'=>'头像',
    'Email'=>'邮箱',
    'Role'=>'角色',

    //Posts
    'Create New Post' => '新建博客',
    'Manage Posts'    => '管理博客',
    'Posts' => '博客',
    
    //其它
    'Remember me next time'=>'下次记住我',
    'Hint'=>'提示',
    'Status'=>'状态',
    'Fields with <span class="required">*</span> are required.'=>'带<span class="required">*</span>为必填栏位。',
    
);
