<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
    'Home' => '首页',

     //动作
    'Login' => '登录',
    'Logout' => '登出',
    'Manage' => '管理',
    'Submit' => '提交',
    'Save' => '保存',
    'Create' => '创建',
    'Update' => '更新',
    'Delete' => '删除',
    
     //用户功能
    'User Menu' => '用户菜单',

     //用户
    'Users' => '用户',
    'Username' => '用户名',
    'Password' => '密码',
    'Nickname' => '昵称',
    'Avatar' => '头像',
    'Email' => '邮箱',
    'Role' => '角色',

    //Posts
    'Create New Post' => '新建文章',
    'Manage Posts'    => '管理文章',
    'Posts' => '文章',
    'Title' => '标题',
    'Excerpt' => '摘要',
    'Content' => '内容',
    'Optimization' => '优化',
    'Privacy' => '私隐',
    'Slug' => '别名',
    'Read Count' => '阅读数',
    'Description' => '描述',
    'Keywords' => '关键词',
    'Created' => '创建时间',
    'Updated' => '更新时间',
    'Categories'=>'文章分类',
    'Edit'=>'编辑',
    'Views'=>'阅读数',
    'ID' => '序号',
    
    //Comments
    'Ping' => '评分',
    'Comments' => '评论',
    // Tags
    'Tag Cloud'=>'标签云',
    //Category
    'Categories'=>'分类',
    'Monthly Archives'=>'文章归档',
    
    //其它
    'Contact Us' => '联系我们',
    'About Me' => '关于我',
    'Remember me next time'=>'下次记住我',
    'Hint'=>'提示',
    'Status'=>'状态',
    'Fields with <span class="required">*</span> are required.'=>'带<span class="required">*</span>为必填栏位。',
    
);
